debug: true

info:
  app:
    name: demo
    description: This is japi-demo
    version: 1.0

server:
  port: 6001
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /
    jsp:
      init-parameters:
        development: true


spring:
  application:
    name: japi-demo
  profiles:
    active: dev
  http:
    encoding:
      charset: utf-8
      force: true
      enable: true
  mvc:
    static-path-pattern: /**
    throw-exception-if-no-handler-found: true


# 日志配置
logging:
  level:
    #    root: ERROR
    tech.rizon.local.dataCenter: INFO
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    file: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"


